# Generated by Django 3.2.8 on 2021-10-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prescriptions', '0004_alter_prescription_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinequantity',
            name='medicine_cart',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Prescriptions.medicinecart'),
        ),
        migrations.AlterField(
            model_name='medicinequantity',
            name='prescription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Prescriptions.prescription'),
        ),
    ]
